PAGE = r'''<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#F5F8FC">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="apple-mobile-web-app-title" content="Proxy Pilot">
  <link rel="manifest" href="/manifest.webmanifest">
  <link rel="icon" href="/static/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/static/icon-192.png">
  <meta name="description" content="Proxy Pilot дважды проверяет MTProto-прокси и помогает настроить резервы в Telegram без регистрации.">
  <link rel="canonical" href="https://distantlivework-creator.github.io/proxy-pilot/">
  <meta property="og:title" content="Proxy Pilot — проверенные MTProto-прокси">
  <meta property="og:description" content="Выбор, двойная проверка и три резерва для Telegram.">
  <title>MTProto-прокси для Telegram — Proxy Pilot</title>
  <style>
    :root{color-scheme:light;--canvas:#f5f8fc;--paper:#fff;--ink:#19334d;--muted:#52677e;--line:#dfe7f0;--blue:#1769d2;--green:#087f5b;--red:#c92a43;--shadow:0 24px 60px rgba(25,51,77,.1)}
    *{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,ui-rounded,"SF Pro Rounded","Segoe UI",system-ui,sans-serif;background:var(--canvas);color:var(--ink)}button,input{font:inherit}button{cursor:pointer}
    body{min-height:100svh}.app{width:min(100%,580px);min-height:100svh;margin:auto;padding:max(22px,env(safe-area-inset-top)) 22px max(22px,env(safe-area-inset-bottom));display:flex;flex-direction:column}
    header{position:sticky;top:max(8px,env(safe-area-inset-top));z-index:20;display:flex;align-items:center;min-height:52px;padding:6px 8px;border:1px solid rgba(223,231,240,.85);border-radius:16px;background:rgba(255,255,255,.88);backdrop-filter:blur(14px);box-shadow:0 8px 24px rgba(25,51,77,.06)}.brand{display:flex;align-items:center;gap:9px;font-size:12px;font-weight:800;letter-spacing:.1em;white-space:nowrap}.mark{height:32px;min-width:54px;padding:0 7px;border-radius:10px;background:var(--ink);display:flex;align-items:center;gap:6px;color:white}.mark b{font-size:15px;letter-spacing:-.08em}.signal{height:15px;display:flex;align-items:flex-end;gap:2px}.signal i{display:block;width:3px;border-radius:3px;background:#36e0ad}.signal i:nth-child(1){height:5px}.signal i:nth-child(2){height:10px}.signal i:nth-child(3){height:15px}
    .guide-btn{margin-left:auto;min-height:38px;border:0;border-radius:11px;background:#e8f1ff;color:#1759ad;padding:0 12px;font-size:12px;font-weight:800;white-space:nowrap}.icon-btn{width:42px;height:42px;border:0;border-radius:50%;background:transparent;color:var(--ink);font-size:20px}.install{margin-left:4px;border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:11px;padding:9px 10px;font-size:12px;font-weight:700;display:none}
    .hero{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:34px 0 28px}.kicker{font-size:13px;font-weight:750;color:var(--green);letter-spacing:.08em;text-transform:uppercase}.hero h1{font-size:clamp(29px,8vw,42px);line-height:1.08;letter-spacing:-.045em;margin:12px 0 10px}.explain{color:var(--muted);font-size:15px;line-height:1.5;margin:0;max-width:360px}
    .power-wrap{position:relative;margin:42px 0 24px}.power-wrap:before,.power-wrap:after{content:"";position:absolute;inset:-13px;border-radius:50%;border:1px solid color-mix(in srgb,var(--green) 28%,transparent)}.power-wrap:after{inset:-28px;border-color:color-mix(in srgb,var(--green) 12%,transparent)}
    .power{position:relative;z-index:1;width:178px;height:178px;border-radius:50%;border:0;background:var(--green);color:white;box-shadow:0 18px 40px color-mix(in srgb,var(--green) 30%,transparent);transition:transform .16s ease,box-shadow .16s ease,background-color .16s ease}.power:hover{background:#066c4d;transform:translateY(-2px);box-shadow:0 24px 50px rgba(8,127,91,.42),0 0 0 8px rgba(8,127,91,.08)}.power:active{background:#05573f;transform:scale(.97)}.power:disabled{background:var(--paper);color:var(--muted);box-shadow:0 12px 32px rgba(25,51,77,.08);border:2px solid var(--line);cursor:default}.power-logo{display:flex;align-items:center;justify-content:center;gap:10px}.power-logo b{font-size:42px;letter-spacing:-.1em}.power-logo .signal{height:32px;gap:4px}.power-logo .signal i{width:6px;background:white}.power-logo .signal i:nth-child(1){height:11px}.power-logo .signal i:nth-child(2){height:21px}.power-logo .signal i:nth-child(3){height:32px}.power.loading .power-logo{animation:turn 1.2s linear infinite}.action-label{font-size:13px;letter-spacing:.1em;font-weight:800;color:var(--green);text-transform:uppercase}.action-label.off{color:var(--muted)}
    .proxy{width:100%;display:flex;align-items:center;gap:13px;text-align:left;padding:16px 17px;background:var(--paper);border:1px solid var(--line);border-radius:17px;box-shadow:0 9px 28px rgba(25,51,77,.05)}.dot{width:10px;height:10px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px color-mix(in srgb,var(--green) 12%,transparent)}.proxy-main{min-width:0;flex:1}.host{font-family:ui-monospace,"SFMono-Regular",Consolas,monospace;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.reserve{font-size:12px;color:var(--muted);margin-top:4px}.latency{color:var(--green);font-size:14px;font-weight:750}
    .feedback{margin-top:12px;padding:17px;background:#eef8f5;border:1px solid #ccebe1;border-radius:17px;text-align:center}.feedback strong{display:block;margin-bottom:10px}.feedback-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.yes,.no,.reserve-setup,.wizard-primary,.wizard-secondary{min-height:48px;border:0;border-radius:12px;font-weight:750}.yes,.wizard-primary{background:var(--green);color:white}.no,.wizard-secondary{background:var(--paper);color:var(--ink);border:1px solid var(--line)}
    .error{font-size:13px;line-height:1.45;color:var(--red);text-align:center;min-height:20px;margin:12px 8px}.actions{display:grid;grid-template-columns:1fr auto;gap:10px}.check,.next{min-height:56px;border:0;border-radius:15px;font-weight:750;font-size:16px}.check{background:var(--ink);color:white}.next{display:none;background:#e6eef7;color:var(--ink);padding:0 18px}.check:disabled{opacity:.55}.reserve-setup{display:none;width:100%;margin-top:10px;background:#e8f1ff;color:#1759ad}.foot{text-align:center;margin:14px 0 0;color:var(--muted);font-size:11px;line-height:1.5}
    dialog{border:0;border-radius:22px;padding:0;width:min(calc(100% - 32px),460px);color:var(--ink);box-shadow:var(--shadow)}dialog::backdrop{background:rgba(25,51,77,.38);backdrop-filter:blur(3px)}.dialog-body{padding:24px}.dialog-body h2{margin:0 0 7px;font-size:21px}.dialog-body p{color:var(--muted);font-size:14px;line-height:1.45}.channels,.notice{background:var(--canvas);border-radius:12px;padding:12px;font-size:12px;line-height:1.5;word-break:break-word}.channels{font-family:ui-monospace,monospace}.notice{font-family:inherit;margin-top:12px}.dialog-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.close{min-width:96px;min-height:48px;border:0;border-radius:12px;background:var(--ink);color:white;font-weight:700}.ios-help{display:none;background:#eef5ff;border-radius:12px;padding:12px;margin-top:12px;color:var(--ink)!important}.wizard-progress{font-size:12px;font-weight:800;color:var(--green);text-transform:uppercase;letter-spacing:.06em}.wizard-buttons{display:grid;gap:10px;margin-top:16px}.wizard-confirm{display:none;grid-template-columns:1fr 1fr;gap:10px}.auto-steps{display:none;background:#eef5ff;border-radius:14px;padding:14px;margin-top:14px;font-size:13px;line-height:1.55}.security{font-size:12px!important}
    .guide-dialog{width:min(calc(100% - 24px),680px);max-height:calc(100svh - 24px);overflow:auto;background:var(--canvas)}.guide-body{padding:28px}.guide-hero{text-align:center;padding:18px 8px 24px}.guide-hero .kicker{display:block}.guide-hero h2{font-size:clamp(30px,7vw,46px);line-height:1.05;letter-spacing:-.045em;margin:12px 0}.guide-hero p{max-width:500px;margin:0 auto;color:var(--muted);line-height:1.55}.guide-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.guide-card{padding:16px;background:var(--paper);border:1px solid var(--line);border-radius:16px}.guide-card strong{display:block;margin-bottom:6px}.guide-card span{color:var(--muted);font-size:12px;line-height:1.45}.guide-section{padding:26px 0;border-top:1px solid var(--line)}.guide-section h3{margin:0 0 14px;font-size:22px}.guide-steps{display:grid;gap:10px;counter-reset:steps}.guide-step{display:grid;grid-template-columns:36px 1fr;gap:12px;align-items:start;padding:14px;background:var(--paper);border-radius:14px;border:1px solid var(--line)}.guide-step:before{counter-increment:steps;content:counter(steps);width:32px;height:32px;display:grid;place-items:center;border-radius:50%;background:var(--blue);color:white;font-weight:850}.guide-step strong{display:block;margin-bottom:3px}.guide-step span{color:var(--muted);font-size:13px;line-height:1.45}.faq details{background:var(--paper);border:1px solid var(--line);border-radius:13px;padding:14px 16px;margin-top:9px}.faq summary{cursor:pointer;font-weight:750}.faq p{margin:10px 0 0!important}.guide-cta{padding:22px;border-radius:18px;background:var(--ink);color:white;text-align:center}.guide-cta h3{margin:0 0 6px}.guide-cta p{color:#cbd7e3;margin:0 0 16px}.guide-cta-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.guide-cta button{min-height:50px;border:0;border-radius:12px;font-weight:800}.guide-start{background:var(--green);color:white}.guide-reserves{background:white;color:var(--ink)}
    @keyframes turn{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}@media(max-width:480px){.brand{font-size:0}.guide-btn{padding:0 9px}.guide-grid{grid-template-columns:1fr}.guide-cta-actions{grid-template-columns:1fr}}@media(min-width:760px){body{display:grid;place-items:center;padding:28px}.app{min-height:min(820px,calc(100svh - 56px));border:1px solid var(--line);border-radius:30px;background:color-mix(in srgb,var(--canvas) 82%,white);box-shadow:var(--shadow)}}@media(min-width:1800px) and (min-height:1000px){.app{transform:scale(1.15)}}@media(min-width:2800px) and (min-height:1600px){.app{transform:scale(1.65)}}
    :focus-visible{outline:3px solid color-mix(in srgb,var(--blue) 45%,transparent);outline-offset:3px}
  </style>
</head>
<body><main class="app">
  <header><div class="brand"><span class="mark" aria-label="Proxy Pilot"><b>PP</b><span class="signal" aria-hidden="true"><i></i><i></i><i></i></span></span>PROXY PILOT</div><button id="guideButton" class="guide-btn" aria-label="Как пользоваться">Инструкция</button><button id="install" class="install">Установить</button><button id="settings" class="icon-btn" aria-label="О приложении">•••</button></header>
  <section class="hero">
    <div id="kicker" class="kicker">Три проверенных резерва</div><h1 id="title">Настроить 3 прокси для Telegram</h1><p id="explain" class="explain">Мастер по очереди откроет три адреса. Добавьте каждый — Telegram сможет переключаться между ними.</p>
    <div class="power-wrap"><button id="power" class="power" aria-label="Начать настройку трёх резервных прокси"><span class="power-logo" aria-hidden="true"><b>PP</b><span class="signal"><i></i><i></i><i></i></span></span></button></div>
    <div id="action" class="action-label">Начать настройку</div>
  </section>
  <section id="proxy" class="proxy" hidden><span class="dot"></span><div class="proxy-main"><div id="host" class="host"></div><div id="reserve" class="reserve"></div></div><div id="latency" class="latency"></div></section>
  <section id="feedback" class="feedback" hidden aria-live="polite"><strong>Щит с галочкой появился в Telegram?</strong><div class="feedback-actions"><button id="connected" class="yes">Да, работает</button><button id="failed" class="no">Нет, другой</button></div><p><a id="telegramFallback" target="_blank" rel="noopener">Telegram не открылся? Открыть веб-ссылку</a></p></section>
  <div id="error" class="error" aria-live="polite"></div><div class="actions"><button id="check" class="check">Обновить список прокси</button></div><p class="foot">Проверка Telegram MTProto · без входа в аккаунт · вкладку можно закрыть</p>
  <dialog id="about" aria-labelledby="aboutTitle"><div class="dialog-body"><h2 id="aboutTitle">Proxy Pilot</h2><p>Сервис собирает адреса из публичных веб-источников, дважды проверяет MTProto и предлагает стабильные резервы.</p><div id="systemHealth" class="notice" aria-live="polite">Состояние каталога загружается…</div><div id="channels" class="channels">Источники не заданы</div><p class="security">Прокси принадлежат сторонним операторам. Они видят ваш IP и факт использования Telegram, но не содержимое зашифрованных чатов. Сайт не может увидеть внутренний статус Telegram или точный расход лимита GitHub Pages.</p><p id="iosHelp" class="ios-help">На iPhone откройте меню «Поделиться» в Safari и выберите «На экран Домой».</p><div class="dialog-actions"><button class="close" id="close">Готово</button></div></div></dialog>
  <dialog id="reserveWizard" aria-labelledby="wizardTitle"><div class="dialog-body"><div id="wizardProgress" class="wizard-progress">Резерв 1 из 3</div><h2 id="wizardTitle">Добавьте первый резерв</h2><p id="wizardText">Telegram сохранит его в списке прокси.</p><div id="wizardProxy" class="notice"></div><div id="autoSteps" class="auto-steps"><strong>Включите автопереключение:</strong><br>Android/iPhone: Настройки → Данные и память → Прокси → <strong>Автопереключение</strong>.<br><br>Mac/Windows: Настройки → Продвинутые настройки → Тип соединения → Прокси → <strong>Auto-Switch</strong>.</div><div class="wizard-buttons"><button id="wizardSend" class="wizard-primary">Открыть в Telegram</button><div id="wizardConfirm" class="wizard-confirm"><button id="wizardYes" class="yes">Добавлен</button><button id="wizardNo" class="no">Не сработал</button></div><button id="wizardClose" class="wizard-secondary">Закрыть</button></div></div></dialog>
  <dialog id="guide" class="guide-dialog"><div class="guide-body"><div class="guide-hero"><span class="kicker">Инструкция на 2 минуты</span><h2>Telegram с рабочим прокси без ручного поиска</h2><p>Proxy Pilot сам отбирает адреса, дважды проверяет их через Telegram и помогает настроить резервы.</p></div><div class="guide-grid"><div class="guide-card"><strong>Без регистрации</strong><span>Не нужен вход в Telegram или платёжная карта.</span></div><div class="guide-card"><strong>Двойная проверка</strong><span>Публикуются только адреса, дважды ответившие Telegram.</span></div><div class="guide-card"><strong>3 резерва</strong><span>Telegram сможет автоматически переключаться между ними.</span></div></div><section class="guide-section"><h3>Как это работает</h3><div class="guide-steps"><div class="guide-step"><div><strong>Нажмите «Добавить»</strong><span>Сайт передаст лучший адрес в официальный Telegram.</span></div></div><div class="guide-step"><div><strong>Подтвердите в Telegram</strong><span>Нажмите «Подключить». Щит с галочкой над чатами означает успех.</span></div></div><div class="guide-step"><div><strong>Добавьте три резерва</strong><span>Мастер пошагово добавит три разных адреса.</span></div></div><div class="guide-step"><div><strong>Включите Auto-Switch</strong><span>Если один адрес отвалится, Telegram сам попробует следующий. Сайт можно закрыть.</span></div></div></div></section><section class="guide-section faq"><h3>Частые вопросы</h3><details><summary>Нужно ли держать сайт открытым?</summary><p>Нет. После добавления прокси работает внутри Telegram.</p></details><details><summary>Может ли Proxy Pilot сам переключить Telegram?</summary><p>Сайт не имеет доступа к настройкам другого приложения. Для этого нужна функция Auto-Switch в Telegram.</p></details><details><summary>Что делать, если прокси не подключился?</summary><p>Вернитесь на сайт и нажмите «Нет, другой». Адрес будет скрыт на 24 часа.</p></details><details><summary>Это бесплатно?</summary><p>Да. Регистрация и платёжные данные не нужны.</p></details><details><summary>Насколько это безопасно?</summary><p>Публичный оператор видит IP и факт использования Telegram, но не содержимое зашифрованных чатов.</p></details></section><div class="guide-cta"><h3>Готовы настроить?</h3><p>Начните с одного адреса или сразу добавьте три резерва.</p><div class="guide-cta-actions"><button id="guideStart" class="guide-start">Добавить лучший</button><button id="guideReserve" class="guide-reserves">Настроить 3 резерва</button></div></div><div class="dialog-actions"><button id="guideClose" class="close">Закрыть</button></div></div></dialog>
</main><script>
const $=s=>document.querySelector(s);const BLOCK_MS=24*60*60*1000;const BLOCK_KEY='proxyPilotBlockedV1';const INSTALLED_KEY='proxyPilotInstalledV1';let best=null,catalog=[],catalogIndex=0,catalogUpdatedAt=null,systemHealth={},deferredInstall=null,staticMode=false,reservePool=[],reserveStep=0;
async function api(path,opts){const r=await fetch(path,opts);const data=await r.json();if(!r.ok)throw new Error(data.detail||'Ошибка сервера');return data}
function proxyKey(p){return `${String(p.host).toLowerCase()}:${p.port}:${String(p.secret).toLowerCase()}`}
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch(_){return fallback}}
function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(_){}}
function blockedMap(){const now=Date.now(),map=readStore(BLOCK_KEY,{});for(const [key,until] of Object.entries(map))if(until<=now)delete map[key];writeStore(BLOCK_KEY,map);return map}
function isBlocked(p){return (blockedMap()[proxyKey(p)]||0)>Date.now()}
function blockProxy(p){const map=blockedMap();map[proxyKey(p)]=Date.now()+BLOCK_MS;writeStore(BLOCK_KEY,map)}
function rememberInstalled(p){const saved=readStore(INSTALLED_KEY,[]);const key=proxyKey(p);if(!saved.includes(key))saved.push(key);writeStore(INSTALLED_KEY,saved.slice(-30))}
function tgUrl(p){const q=new URLSearchParams({server:p.host,port:p.port,secret:p.secret});return `tg://proxy?${q}`}
function webTgUrl(p){const q=new URLSearchParams({server:p.host,port:p.port,secret:p.secret});return `https://t.me/proxy?${q}`}
function setLoading(on){$('#check').disabled=on;$('#check').textContent=on?'Обновляем…':'Обновить каталог';$('#power').classList.toggle('loading',on)}
function availableIndices(){return catalog.map((p,i)=>isBlocked(p)?-1:i).filter(i=>i>=0)}
function selectInitial(){const available=availableIndices();if(!available.length)return -1;const saved=sessionStorage.getItem('proxyPilotSessionChoice');const savedIndex=catalog.findIndex(p=>proxyKey(p)===saved&&!isBlocked(p));if(savedIndex>=0)return savedIndex;const pool=available.slice(0,Math.min(5,available.length));const picked=pool[Math.floor(Math.random()*pool.length)];sessionStorage.setItem('proxyPilotSessionChoice',proxyKey(catalog[picked]));return picked}
function selectNext(){if(!catalog.length)return -1;for(let offset=1;offset<=catalog.length;offset++){const i=(catalogIndex+offset)%catalog.length;if(!isBlocked(catalog[i]))return i}return -1}
function connectionText(p){const seconds=p.latency_ms==null?null:(p.latency_ms/1000).toFixed(1).replace('.',',');return seconds?`проверка ~${seconds} с`:'—'}
function cycleWord(n){const n10=n%10,n100=n%100;return n10===1&&n100!==11?'цикл':n10>=2&&n10<=4&&(n100<12||n100>14)?'цикла':'циклов'}
function stabilityText(p){const streak=Math.max(1,Number(p.success_streak||1));const checks=Math.max(1,Number(p.checks_passed||1));return `${checks} MTProto-проверки · ${streak} ${cycleWord(streak)} подряд`}
function renderCurrent(){const p=catalogIndex>=0?catalog[catalogIndex]:null;render(p?{...p,ready:true}:{ready:false},$('#channels').textContent)}
function render(c,sourceText){best=c.ready?c:null;$('#channels').textContent=sourceText||'Источники не заданы';const ready=!!best;const stale=catalogUpdatedAt&&Date.now()-catalogUpdatedAt.getTime()>45*60*1000;const protectedMode=!!systemHealth.protect_new_connections&&readStore(INSTALLED_KEY,[]).length===0;$('#power').disabled=!ready||protectedMode;$('#proxy').hidden=!ready;$('#action').classList.toggle('off',!ready||protectedMode);$('#action').textContent=protectedMode?'Защитный режим':ready?'Начать настройку':'Прокси пока нет';$('#kicker').textContent=protectedMode?'Защита каталога':ready?(stale?'Каталог устарел':'Три проверенных резерва'):'Нет соединения';$('#title').textContent=protectedMode?'Новые подключения приостановлены':ready?'Настроить 3 прокси для Telegram':'Ищем рабочие прокси';$('#explain').textContent=protectedMode?'Подтверждённых резервов слишком мало. Уже добавленные прокси продолжат работать в Telegram.':ready?'Мастер по очереди откроет три адреса. Добавьте каждый — Telegram сможет переключаться между ними.':'Обновите каталог или попробуйте позже.';if(ready){$('#host').textContent='Три резервных адреса готовы';$('#latency').textContent='готово';$('#reserve').textContent=`${availableIndices().length} адресов дважды проверены` }$('#error').textContent=protectedMode?'Сервис сам откроет доступ, когда появятся минимум 3 резерва.':stale?'Данные старше 45 минут. Обновите каталог.':''}
function openTelegram(){if(!best)return;$('#telegramFallback').href=webTgUrl(best);$('#feedback').hidden=false;$('#kicker').textContent='Открываем Telegram';$('#title').textContent='Проверьте щит с галочкой';$('#explain').textContent='Нажмите «Подключить» в Telegram, затем вернитесь сюда.';$('#action').textContent='Открыть снова';location.href=tgUrl(best)}
function markConnected(){if(!best)return;rememberInstalled(best);$('#feedback').hidden=true;$('#kicker').textContent='Готово';$('#title').textContent='Прокси сохранён в Telegram';$('#explain').textContent='Щит с галочкой подтверждает подключение. Страницу можно закрыть.';$('#action').textContent='Добавить снова'}
function markFailed(){if(!best)return;blockProxy(best);$('#feedback').hidden=true;const next=selectNext();catalogIndex=next;if(next<0){render({ready:false},$('#channels').textContent);$('#error').textContent='На этом устройстве все адреса отклонены.';return}renderCurrent();$('#error').textContent='Нерабочий адрес скрыт на 24 часа. Выбран следующий.'}
async function loadCatalog(){const r=await fetch('./data/proxies.json',{cache:'no-cache'});if(!r.ok)throw new Error('Каталог пока недоступен');const data=await r.json();catalog=(Array.isArray(data)?data:(data.proxies||[])).map(p=>({...p,key:proxyKey(p)}));catalogUpdatedAt=data.updated_at?new Date(data.updated_at):null;systemHealth=data.health||{level:catalog.length>=3?'degraded':'critical',protect_new_connections:catalog.length<3,confirmed_proxies:catalog.length};catalogIndex=selectInitial();staticMode=true;const sourceText=(data.sources||[]).map(x=>new URL(x).hostname).join(' · ');const labels={healthy:'норма',degraded:'сниженный резерв',critical:'защитный режим'};$('#systemHealth').textContent=`Состояние каталога: ${labels[systemHealth.level]||systemHealth.level} · ${systemHealth.confirmed_proxies||catalog.length} резервов · ${systemHealth.sources_ok??'?'} из ${systemHealth.sources_total??'?'} источников`;render(catalogIndex>=0?{...catalog[catalogIndex],ready:true}:{ready:false},sourceText)}
async function loadApi(){const [s,c]=await Promise.all([api('/api/status'),api('/api/connection')]);catalog=[];catalogUpdatedAt=null;render({...c,ready:c.ready},s.channels.length?s.channels.map(x=>'@'+x).join(' · '):'Локальный API')}
async function load(){try{await loadCatalog()}catch(_catalogError){try{staticMode=false;await loadApi()}catch(e){$('#error').textContent=e.message}}}
function startWizard(){if(availableIndices().length<3||(systemHealth.protect_new_connections&&readStore(INSTALLED_KEY,[]).length===0)){if($('#guide').open)$('#guide').close();$('#error').textContent='Мастер откроется, когда будут доступны три подтверждённых резерва.';return}const installed=new Set(readStore(INSTALLED_KEY,[]));reservePool=catalog.filter(p=>!isBlocked(p)&&!installed.has(proxyKey(p))).slice(0,3);if(reservePool.length<3)reservePool=catalog.filter(p=>!isBlocked(p)).slice(0,3);reserveStep=0;renderWizard();$('#reserveWizard').showModal()}
function renderWizard(){const done=reserveStep>=3||reserveStep>=reservePool.length;$('#wizardProgress').textContent=done?'Резервы готовы':`Резерв ${reserveStep+1} из 3`;$('#wizardTitle').textContent=done?'Включите автопереключение':`Добавьте резерв №${reserveStep+1}`;$('#wizardText').textContent=done?'Telegram будет сам переходить на следующий адрес, если текущий отвалится.':'Откройте Telegram, добавьте адрес и вернитесь сюда.';$('#wizardProxy').textContent=done?'Три адреса сохранены на этом устройстве.':`${reservePool[reserveStep]?.host||''}:${reservePool[reserveStep]?.port||''}`;$('#wizardSend').style.display=done?'none':'block';$('#wizardConfirm').style.display='none';$('#autoSteps').style.display=done?'block':'none';$('#wizardClose').textContent=done?'Готово':'Закрыть'}
function sendWizardProxy(){const p=reservePool[reserveStep];if(!p)return;$('#wizardSend').style.display='none';$('#wizardConfirm').style.display='grid';location.href=tgUrl(p)}
function wizardSuccess(){const p=reservePool[reserveStep];if(p)rememberInstalled(p);reserveStep+=1;renderWizard()}
function wizardFailure(){const failed=reservePool[reserveStep];if(failed)blockProxy(failed);const used=new Set(reservePool.map(proxyKey));const replacement=catalog.find(p=>!isBlocked(p)&&!used.has(proxyKey(p)));if(replacement)reservePool[reserveStep]=replacement;else reservePool.splice(reserveStep,1);renderWizard()}
$('#power').onclick=startWizard;$('#connected').onclick=markConnected;$('#failed').onclick=markFailed;$('#check').onclick=async()=>{try{setLoading(true);if(!staticMode)await api('/api/sync',{method:'POST'});await load()}catch(e){$('#error').textContent=e.message}finally{setLoading(false)}};
$('#wizardSend').onclick=sendWizardProxy;$('#wizardYes').onclick=wizardSuccess;$('#wizardNo').onclick=wizardFailure;$('#wizardClose').onclick=()=>$('#reserveWizard').close();
$('#autoSteps').innerHTML=`<strong>Включите Auto-Switch:</strong><br>Android: Настройки → Данные и память → Настройки прокси.<br>iPhone: Настройки → Данные и память → Прокси.<br>Mac: Настройки → Данные и память → Использовать прокси.<br>Windows: Настройки → Продвинутые настройки → Тип соединения.<br><br>Затем включите <strong>Auto-Switch Proxies / Автопереключение</strong>.`;
const guideSteps=document.querySelectorAll('#guide .guide-step');guideSteps[0].querySelector('strong').textContent='Нажмите «Начать настройку»';guideSteps[0].querySelector('span').textContent='Мастер подготовит три проверенных адреса и проведёт по каждому шагу.';document.querySelectorAll('#guide .faq details')[2].querySelector('p').textContent='В мастере нажмите «Не сработал». Этот адрес будет скрыт на 24 часа и заменён другим.';
const autoFaq=document.createElement('details');autoFaq.innerHTML=`<summary>Что такое Auto-Switch и как его включить?</summary><p><strong>Auto-Switch</strong> — встроенное автопереключение Telegram. Если активный прокси перестал отвечать, Telegram пробует следующий из трёх сохранённых адресов.<br><br><strong>Android:</strong> Настройки → Данные и память → Настройки прокси.<br><strong>iPhone:</strong> Настройки → Данные и память → Прокси.<br><strong>Mac:</strong> Настройки → Данные и память → Использовать прокси.<br><strong>Windows:</strong> Настройки → Продвинутые настройки → Тип соединения.<br><br>Откройте список прокси и включите <strong>Auto-Switch Proxies / Автопереключение</strong>. После этого сайт можно закрыть.</p>`;$('#guide .faq').append(autoFaq);
const guideTitle=$('#guide h2');guideTitle.id='guideTitle';guideTitle.tabIndex=-1;$('#guide').setAttribute('aria-label','Инструкция Proxy Pilot');$('#about').setAttribute('aria-label','О приложении Proxy Pilot');$('#reserveWizard').setAttribute('aria-label','Настройка трёх резервов');$('#guideStart').textContent='Настроить 3 прокси';$('#guide .guide-cta p').textContent='Мастер пошагово настроит три проверенных резерва.';$('#guideReserve').remove();$('.guide-cta-actions').style.gridTemplateColumns='1fr';$('#guideButton').onclick=()=>{const guide=$('#guide');guide.showModal();guide.scrollTop=0;guideTitle.focus({preventScroll:true})};$('#guideClose').onclick=()=>$('#guide').close();$('#guideStart').onclick=()=>{$('#guide').close();startWizard()};$('#settings').onclick=()=>$('#about').showModal();$('#close').onclick=()=>$('#about').close();window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install').style.display='block'});$('#install').onclick=async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;$('#install').style.display='none'}else $('#about').showModal()};
const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent);if(isiOS&&!window.navigator.standalone){$('#install').style.display='block';$('#iosHelp').style.display='block'}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');load();setInterval(load,300000);
</script></body></html>'''
